version: "3.9"
services:
  server:
    build:
      context: ./server
    image: hello-server
    container_name: hello-server
    ports:
      - "3000:3000"
    environment:
      - PORT=3000

  client:
    build:
      context: ./client
    image: hello-client
    container_name: hello-client
    ports:
      - "8080:80"
    environment:
      # Use service name 'server' as hostname inside the compose network
      - VITE_API_BASE=http://server:3000
    depends_on:
      - server
